name: Daily Delete CSV Files

on:
  schedule:
    - cron: '30 20 * * *'  # Runs every day at 20:30 UTC

jobs:
  delete-todays-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Delete today's edu_adults_contacts CSV files
        run: |
          TODAY=$(date +%Y%m%d)
          echo "Deleting files edu_adults_contacts_${TODAY}_*.csv"
          rm -v contacts/edu_adults_contacts_${TODAY}_*.csv || echo "No files found to delete"
