name: Daily Clean CSV Files

on:
  push:
    branches: ["dev", "master"]
  schedule:
    - cron: '30 07 * * *'  # Runs every day at 20:30 UTC

jobs:
  clean-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Keep only the latest CSV per list
        run: |
          echo "Cleaning CSV files in contacts/ directory..."
          CLEANED_LISTS=""
          FILES_DELETED=0
          LISTS_NO_DELETION=""
          TOTAL_LISTS=0
          TODAY=$(date +%Y%m%d)
          SUMMARY_FILE="cleanup_summary_$TODAY.log"

          echo "Cleanup summary for $TODAY:" > $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE

          # Find all CSVs, strip the timestamp (_YYYYMMDD_HHMMSS.csv), get unique prefixes
          for prefix in $(find contacts -type f -name "*.csv" \
            | sed -E 's/_[0-9]{8}_[0-9]{6}\.csv//' \
            | sort -u); do

            TOTAL_LISTS=$((TOTAL_LISTS + 1))
            BASENAME=$(basename "$prefix")
            echo "Processing list: $BASENAME"

            # Get all files for this prefix, newest first
            FILES=$(ls -t ${prefix}_*.csv 2>/dev/null || true)
            COUNT=$(echo "$FILES" | wc -l)

            if [ "$COUNT" -lt 2 ]; then
              echo "  → Only $COUNT file(s) found, nothing to delete."
              echo "- $BASENAME: kept $COUNT, deleted 0 (no deletion needed)" >> $SUMMARY_FILE
              LISTS_NO_DELETION="$LISTS_NO_DELETION $BASENAME"
              continue
            fi

            echo "  → $COUNT files found, keeping the newest and deleting the rest..."
            KEPT=1
            DELETED=$((COUNT - 1))
            echo "$FILES" | tail -n +2 | xargs -r rm -v
            FILES_DELETED=$((FILES_DELETED + DELETED))

            CLEANED_LISTS="$CLEANED_LISTS $BASENAME"
            echo "- $BASENAME: kept $KEPT, deleted $DELETED" >> $SUMMARY_FILE
          done

          # Prepend a short summary at the top of the file
          TEMP_FILE="temp_$SUMMARY_FILE"
          {
            echo "Daily CSV Cleanup Report for $TODAY"
            echo "-----------------------------------"
            echo "Total lists processed: $TOTAL_LISTS"
            echo "Total files deleted: $FILES_DELETED"
            echo "Lists with no deletion: ${LISTS_NO_DELETION:-None}"
            echo ""
            cat $SUMMARY_FILE
          } > $TEMP_FILE
          mv $TEMP_FILE $SUMMARY_FILE

          # Export environment variables for later steps
          echo "CLEANED_LISTS=$CLEANED_LISTS" >> $GITHUB_ENV
          echo "SUMMARY_FILE=$SUMMARY_FILE" >> $GITHUB_ENV
          echo "FILES_DELETED=$FILES_DELETED" >> $GITHUB_ENV
          echo "TODAY=$TODAY" >> $GITHUB_ENV

          echo ""
          cat $SUMMARY_FILE
          echo ""

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if [ "${FILES_DELETED}" -gt 0 ]; then
            git add contacts/*.csv || echo "No CSV changes to commit"
            git commit -m "Daily cleanup $TODAY: cleaned lists:${CLEANED_LISTS}" || echo "No changes to commit"
            git push
          else
            echo "No files deleted today. Skipping commit and push."
          fi

      - name: Upload cleanup summary
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-summary-${{ github.run_id }}-${{ env.TODAY }}
          path: ${{ env.SUMMARY_FILE }}
          retention-days: 7
