name: Creating_real_csv_contacts_Test

on:
  push:
    branches: ["dev"]
    
  
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in simulation mode'
        required: false
        default: true
        type: boolean
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

# Add permissions required by the reusable workflow
permissions:
  contents: write
  actions: read

jobs:
  # -------------------------------
  # Contact extraction job (calling reusable workflow)
  # -------------------------------
  contact-extraction:
    uses: sednabcn/services/.github/workflows/contact-extractor.yml@dev
    with:
      source_directory: "contact_details"
      output_directory: "contacts"

  # -------------------------------
  # Main campaign job (depends on contact extraction)
  # -------------------------------
  campaign:
    runs-on: ubuntu-latest
    needs: contact-extraction
    
    steps:
      - name: Checkout repository
        uses: sednabcn/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir \
            python-docx pyyaml pandas openpyxl requests jinja2 \
            gspread google-auth google-auth-oauthlib google-auth-httplib2
      # -------------------------------
      # Download contact extraction artifacts
      # -------------------------------
      - name: Download contact extraction results
        uses: actions/download-artifact@v4
        with:
          name: latest-contact-extraction-results
          path: ./contacts

      - name: Debug downloaded artifacts
        run: |
          echo "=== Checking workspace structure ==="
          ls -la ./
          echo ""
          echo "=== Checking contacts directory ==="
          ls -la ./contacts/ || echo "❌ contacts directory not found"
          echo ""
          echo "=== Looking for CSV files anywhere ==="
          find . -name "*.csv" -type f || echo "❌ No CSV files found"
          echo ""
          echo "=== Checking if campaign script exists ==="
          ls -la utils/docx_parser.py || echo "❌ utils/docx_parser.py not found"
      # -------------------------------
      # Campaign Execution
      # -------------------------------
      - name: Create directory structure
        run: |
          mkdir -p contacts campaigns-resutls tracking
          echo "Directory structure ready"

      - name: Use real campaign script
        run: |
          # Check if utils/docx_parser.py exists in repository
          if [ -f "utils/docx_parser.py" ]; then
            echo "✅ Using existing utils/docx_parser.py from repository"
          else
            echo "❌ utils/docx_parser.py not found in repository"
            echo "The real campaign script should be at utils/docx_parser.py"
            exit 1
          fi
